Feature/button component
isdi-coders-2023/coding-adventure-Marc-Girbau-front-202301-BCN pull request #1
Opened 2023-02-27 15:45 UTC by marcgirbaub

2023-02-27 16:07 UTC, benjaminrae requested changes

2023-02-27 16:07 UTC, benjaminrae commented on src/components/Button/ButtonStyled.tsx
> +  color: #1e1e1e;
Los colores no podrian venir de otro sitio?

2023-02-28 10:51 UTC, marcgirbaub commented on src/components/Button/ButtonStyled.tsx
> +  color: #1e1e1e;
He añadido theme provider para los colores y las fuentes de momento.

2023-02-28 11:29 UTC, benjaminrae requested changes

2023-02-28 11:29 UTC, benjaminrae commented on src/styles/types.ts
> +interface CustomTheme {
Mira como tipar el theme

2023-02-28 11:41 UTC, marcgirbaub commented on src/styles/types.ts
> +interface CustomTheme {
He creado un declarations file para tipar el theme.

2023-02-28 11:41 UTC, benjaminrae approved these changes
Sigue con el formulario

2023-02-28 11:42 UTC, merged